# Generated by Django 3.2.6 on 2021-08-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('url', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descripton', models.TextField()),
                ('url', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('year', models.DateTimeField()),
                ('country', models.CharField(max_length=255)),
                ('world_premiere', models.DateTimeField()),
                ('budget', models.IntegerField()),
                ('fees_in_country', models.IntegerField()),
                ('fees_in_world', models.IntegerField()),
                ('actory', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='blog.actor', verbose_name='ACTOR')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds', to='blog.category')),
                ('derictory', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='directory', to='blog.actor', verbose_name='DIRECTOR')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.genre')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=255)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.movie')),
            ],
        ),
    ]
