from django.urls import path
from .views import *

urlpatterns = [
    path('create_category/', CategoryCreateView.as_view()),
    path('update_category/', CategoryUpdateView.as_view()),
    path('list_category/', CategoryListView.as_view()),
    path('destroy_category/', CategoryDestroyView.as_view()),
    path('create_actor/', ActorCreateView.as_view()),
    path('update_actor/', ActorUpdateView.as_view()),
    path('generic_actor/', ActorGenericView.as_view()),
    path('list_actor/', ActorListView.as_view()),
    path('destroy_actor/', ActorDestroyView.as_view()),
    path('create_movie/', MovieCreateView.as_view()),
    path('update_movie/', MovieUpdateView.as_view()),
    path('generic_movie/', MovieGenericView.as_view()),
    path('list_movie/', MovieListView.as_view()),
    path('destroy_movie/', MovieDestroyView.as_view()),
    path('create_genre/', GenreCreateView.as_view()),
    path('update_genre/', GenreUpdateView.as_view()),
    path('generic_genre/', GenreGenericView.as_view()),
    path('list_genre/', GenreListView.as_view()),
    path('destroy_genre/', GenreDestroyView.as_view()),
    path('create_rating/', RatingCreateView.as_view()),
    path('update_rating/', RatingUpdateView.as_view()),
    path('generic_rating/', RatingGenericView.as_view()),
    path('list_rating/', RatingListView.as_view()),
    path('destroy_rating/', RatingDestroyView.as_view()),
    path('create_movieimage/', MovieImageCreateView.as_view()),
    path('update_movieimage/', MovieImageUpdateView.as_view()),
    path('generic_movieimage/', MovieImageGenericView.as_view()),
    path('list_movieimage/', MovieImageListView.as_view()),
    path('destroy_movieimage/', MovieImageDestroyView.as_view()),
    path('create_rewiew/', ReviewCreateView.as_view()),
    path('update_rewiew/', ReviewUpdateView.as_view()),
    path('generic_rewiew/', ReviewGenericView.as_view()),
    path('list_mrewiew/', ReviewListView.as_view()),
    path('destroy_rewiew/', ReviewDestroyView.as_view()),
]